<?php
/** @noinspection SqlNoDataSourceInspection */
/** @noinspection SqlDialectInspection */

// Pulls in headers, connects to MariaDB, and automatically populates $pdo and $current_user_id
require_once 'connect.php';

// Safe extraction of parameters coming via URL query parameters
$translation = $_GET['translation'] ?? '';
$book        = $_GET['book'] ?? '';
$chapter     = $_GET['chapter'] ?? 0;
$startVerse  = $_GET['start'] ?? 0;
$endVerse    = $_GET['end'] ?? 0;

// --- Step 1: Look up book_id inside the shared database ---
$translStmt = $pdo->prepare('SELECT _id FROM book WHERE book_name = ?');
$translStmt->execute([$book]);
$bookRow = $translStmt->fetch();
$bookId = $bookRow ? (int)$bookRow["_id"] : -1;

try {
    // Begin a native SQL transaction block to ensure atomic integrity across tables
    $pdo->beginTransaction();

    // --- Step 2: Insert into the multi-tenant passage table ---
    $statement = $pdo->prepare('
        INSERT INTO passage (user_id, book_id, chapter, start_verse, end_verse) 
        VALUES (?, ?, ?, ?, ?)
    ');
    $statement->execute([
        $current_user_id,
        $bookId,
        $chapter,
        $startVerse,
        $endVerse
    ]);

    // Grab the auto-incremented primary key generated by MariaDB
    $passageId = (int)$pdo->lastInsertId();

    // --- Step 3: Insert into the memory_passage table ---
    // Note: The 'queued' column was dropped from your target MariaDB schema definition
    $statement = $pdo->prepare('
        INSERT INTO memory_passage (user_id, passage_id, preferred_translation_cd, frequency_days) 
        VALUES (?, ?, ?, 1)
    ');
    $statement->execute([
        $current_user_id,
        $passageId,
        $translation
    ]);

    // Commit changes safely to MariaDB
    $pdo->commit();

    echo json_encode($passageId);

} catch (Exception $e) {
    // Roll back changes if any step in the sequence fails
    if ($pdo->inTransaction()) {
        $pdo->rollBack();
    }
    error_log("An error occurred in adding a passage: " . $e->getMessage());
    http_response_code(500);
    echo json_encode("error");
}
